import * as z from "zod";

export const FormatSchema = z.enum(["gguf"]);
export type Format = z.infer<typeof FormatSchema>;

export const QuantizationLevelSchema = z.enum(["Q4_0", "Q4_K_M", "Q8_0"]);
export type QuantizationLevel = z.infer<typeof QuantizationLevelSchema>;

export const DetailsSchema = z.object({
    parent_model: z.string(),
    format: FormatSchema,
    family: z.string(),
    families: z.array(z.string()),
    parameter_size: z.string(),
    quantization_level: QuantizationLevelSchema,
});
export type Details = z.infer<typeof DetailsSchema>;

export const ModelSchema = z.object({
    name: z.string(),
    model: z.string(),
    modified_at: z.coerce.date(),
    size: z.number(),
    digest: z.string(),
    details: DetailsSchema,
});
export type Model = z.infer<typeof ModelSchema>;

export const ModelsResponseSchema = z.object({
    models: z.array(ModelSchema),
});
export type ModelsResponse = z.infer<typeof ModelsResponseSchema>;

export const CapabilitySchema = z.enum(["completion", "thinking", "tools", "vision"]);
export type Capability = z.infer<typeof CapabilitySchema>;

export const TokenizerGgmlModelSchema = z.enum(["gpt2", "llama"]);
export type TokenizerGgmlModel = z.infer<typeof TokenizerGgmlModelSchema>;

export const TokenizerGgmlPreSchema = z.enum(["dbrx", "default", "gpt-4o", "qwen2"]);
export type TokenizerGgmlPre = z.infer<typeof TokenizerGgmlPreSchema>;

export const TypeSchema = z.enum(["F16", "F32", "Q4_0", "Q4_K", "Q5_0", "Q5_K", "Q6_K", "Q8_0"]);
export type Type = z.infer<typeof TypeSchema>;

export const DetailsClassSchema = z.object({
    parent_model: z.string(),
    format: FormatSchema,
    family: z.string(),
    families: z.array(z.string()),
    parameter_size: z.string(),
    quantization_level: QuantizationLevelSchema,
});
export type DetailsClass = z.infer<typeof DetailsClassSchema>;

export const ModelInfoSchema = z.object({
    "general.architecture": z.string(),
    "general.basename": z.string().optional(),
    "general.file_type": z.number(),
    "general.finetune": z.string().optional(),
    "general.languages": z.null().optional(),
    "general.license": z.string().optional(),
    "general.license.link": z.string().optional(),
    "general.parameter_count": z.number(),
    "general.quantization_version": z.number(),
    "general.size_label": z.string().optional(),
    "general.tags": z.null().optional(),
    "general.type": z.string().optional(),
    "phi3.attention.head_count": z.number().optional(),
    "phi3.attention.head_count_kv": z.number().optional(),
    "phi3.attention.layer_norm_rms_epsilon": z.number().optional(),
    "phi3.attention.sliding_window": z.number().optional(),
    "phi3.block_count": z.number().optional(),
    "phi3.context_length": z.number().optional(),
    "phi3.embedding_length": z.number().optional(),
    "phi3.feed_forward_length": z.number().optional(),
    "phi3.rope.dimension_count": z.number().optional(),
    "phi3.rope.freq_base": z.number().optional(),
    "phi3.rope.scaling.attn_factor": z.number().optional(),
    "phi3.rope.scaling.original_context_length": z.number().optional(),
    "tokenizer.ggml.add_bos_token": z.boolean().optional(),
    "tokenizer.ggml.add_eos_token": z.boolean().optional(),
    "tokenizer.ggml.bos_token_id": z.number().optional(),
    "tokenizer.ggml.eos_token_id": z.number(),
    "tokenizer.ggml.model": TokenizerGgmlModelSchema,
    "tokenizer.ggml.padding_token_id": z.number().optional(),
    "tokenizer.ggml.pre": TokenizerGgmlPreSchema.optional(),
    "tokenizer.ggml.scores": z.null().optional(),
    "tokenizer.ggml.token_type": z.null(),
    "tokenizer.ggml.tokens": z.null(),
    "tokenizer.ggml.unknown_token_id": z.number().optional(),
    "llama.attention.head_count": z.number().optional(),
    "llama.attention.head_count_kv": z.number().optional(),
    "llama.attention.layer_norm_rms_epsilon": z.number().optional(),
    "llama.block_count": z.number().optional(),
    "llama.context_length": z.number().optional(),
    "llama.embedding_length": z.number().optional(),
    "llama.feed_forward_length": z.number().optional(),
    "llama.rope.dimension_count": z.number().optional(),
    "llama.rope.freq_base": z.number().optional(),
    "granitehybrid.attention.head_count": z.number().optional(),
    "granitehybrid.attention.head_count_kv": z.null().optional(),
    "granitehybrid.attention.layer_norm_rms_epsilon": z.number().optional(),
    "granitehybrid.attention.scale": z.number().optional(),
    "granitehybrid.block_count": z.number().optional(),
    "granitehybrid.context_length": z.number().optional(),
    "granitehybrid.embedding_length": z.number().optional(),
    "granitehybrid.embedding_scale": z.number().optional(),
    "granitehybrid.expert_count": z.number().optional(),
    "granitehybrid.expert_shared_feed_forward_length": z.number().optional(),
    "granitehybrid.expert_used_count": z.number().optional(),
    "granitehybrid.feed_forward_length": z.number().optional(),
    "granitehybrid.logit_scale": z.number().optional(),
    "granitehybrid.residual_scale": z.number().optional(),
    "granitehybrid.rope.dimension_count": z.number().optional(),
    "granitehybrid.rope.freq_base": z.number().optional(),
    "granitehybrid.rope.scaling.finetuned": z.boolean().optional(),
    "granitehybrid.ssm.conv_kernel": z.number().optional(),
    "granitehybrid.ssm.group_count": z.number().optional(),
    "granitehybrid.ssm.inner_size": z.number().optional(),
    "granitehybrid.ssm.state_size": z.number().optional(),
    "granitehybrid.ssm.time_step_rank": z.number().optional(),
    "granitehybrid.vocab_size": z.number().optional(),
    "tokenizer.ggml.merges": z.null().optional(),
    "qwen3.attention.head_count": z.number().optional(),
    "qwen3.attention.head_count_kv": z.number().optional(),
    "qwen3.attention.key_length": z.number().optional(),
    "qwen3.attention.layer_norm_rms_epsilon": z.number().optional(),
    "qwen3.attention.value_length": z.number().optional(),
    "qwen3.block_count": z.number().optional(),
    "qwen3.context_length": z.number().optional(),
    "qwen3.embedding_length": z.number().optional(),
    "qwen3.feed_forward_length": z.number().optional(),
    "qwen3.rope.freq_base": z.number().optional(),
    "qwen3.rope.scaling.factor": z.number().optional(),
    "qwen3.rope.scaling.original_context_length": z.number().optional(),
    "qwen3.rope.scaling.type": z.string().optional(),
    "qwen2.attention.head_count": z.number().optional(),
    "qwen2.attention.head_count_kv": z.number().optional(),
    "qwen2.attention.layer_norm_rms_epsilon": z.number().optional(),
    "qwen2.block_count": z.number().optional(),
    "qwen2.context_length": z.number().optional(),
    "qwen2.embedding_length": z.number().optional(),
    "qwen2.feed_forward_length": z.number().optional(),
    "qwen2.rope.freq_base": z.number().optional(),
    "qwen25vl.attention.head_count": z.number().optional(),
    "qwen25vl.attention.head_count_kv": z.number().optional(),
    "qwen25vl.attention.layer_norm_rms_epsilon": z.number().optional(),
    "qwen25vl.block_count": z.number().optional(),
    "qwen25vl.context_length": z.number().optional(),
    "qwen25vl.embedding_length": z.number().optional(),
    "qwen25vl.feed_forward_length": z.number().optional(),
    "qwen25vl.rope.freq_base": z.number().optional(),
    "qwen25vl.rope.mrope_section": z.null().optional(),
    "qwen25vl.vision.attention.head_count": z.number().optional(),
    "qwen25vl.vision.attention.layer_norm_epsilon": z.number().optional(),
    "qwen25vl.vision.block_count": z.number().optional(),
    "qwen25vl.vision.embedding_length": z.number().optional(),
    "qwen25vl.vision.fullatt_block_indexes": z.null().optional(),
    "qwen25vl.vision.num_channels": z.number().optional(),
    "qwen25vl.vision.patch_size": z.number().optional(),
    "qwen25vl.vision.rope.freq_base": z.number().optional(),
    "qwen25vl.vision.spatial_merge_size": z.number().optional(),
    "qwen25vl.vision.spatial_patch_size": z.number().optional(),
    "qwen25vl.vision.temporal_patch_size": z.number().optional(),
    "qwen25vl.vision.window_size": z.number().optional(),
    "tokenizer.ggml.add_padding_token": z.boolean().optional(),
    "qwen3vl.attention.head_count": z.number().optional(),
    "qwen3vl.attention.head_count_kv": z.number().optional(),
    "qwen3vl.attention.key_length": z.number().optional(),
    "qwen3vl.attention.layer_norm_rms_epsilon": z.number().optional(),
    "qwen3vl.attention.value_length": z.number().optional(),
    "qwen3vl.block_count": z.number().optional(),
    "qwen3vl.context_length": z.number().optional(),
    "qwen3vl.embedding_length": z.number().optional(),
    "qwen3vl.feed_forward_length": z.number().optional(),
    "qwen3vl.rope.freq_base": z.number().optional(),
    "qwen3vl.vision.attention.head_count": z.number().optional(),
    "qwen3vl.vision.attention.layer_norm_epsilon": z.number().optional(),
    "qwen3vl.vision.block_count": z.number().optional(),
    "qwen3vl.vision.deepstack_visual_indexes": z.null().optional(),
    "qwen3vl.vision.embedding_length": z.number().optional(),
    "qwen3vl.vision.image_mean": z.null().optional(),
    "qwen3vl.vision.image_std": z.null().optional(),
    "qwen3vl.vision.longest_edge": z.number().optional(),
    "qwen3vl.vision.num_channels": z.number().optional(),
    "qwen3vl.vision.patch_size": z.number().optional(),
    "qwen3vl.vision.rope.freq_base": z.number().optional(),
    "qwen3vl.vision.shortest_edge": z.number().optional(),
    "qwen3vl.vision.spatial_merge_size": z.number().optional(),
    "qwen3vl.vision.temporal_patch_size": z.number().optional(),
    "tokenizer.ggml.eos_token_ids": z.null().optional(),
    "llama.vocab_size": z.number().optional(),
    "gemma3.attention.head_count": z.number().optional(),
    "gemma3.attention.head_count_kv": z.number().optional(),
    "gemma3.attention.key_length": z.number().optional(),
    "gemma3.attention.layer_norm_rms_epsilon": z.number().optional(),
    "gemma3.attention.sliding_window": z.number().optional(),
    "gemma3.attention.value_length": z.number().optional(),
    "gemma3.block_count": z.number().optional(),
    "gemma3.context_length": z.number().optional(),
    "gemma3.embedding_length": z.number().optional(),
    "gemma3.feed_forward_length": z.number().optional(),
    "gemma3.mm.tokens_per_image": z.number().optional(),
    "gemma3.rope.freq_base": z.number().optional(),
    "gemma3.rope.scaling.factor": z.number().optional(),
    "gemma3.rope.scaling.type": z.string().optional(),
    "gemma3.vision.attention.head_count": z.number().optional(),
    "gemma3.vision.attention.layer_norm_epsilon": z.number().optional(),
    "gemma3.vision.block_count": z.number().optional(),
    "gemma3.vision.embedding_length": z.number().optional(),
    "gemma3.vision.feed_forward_length": z.number().optional(),
    "gemma3.vision.image_size": z.number().optional(),
    "gemma3.vision.num_channels": z.number().optional(),
    "gemma3.vision.patch_size": z.number().optional(),
    "tokenizer.ggml.add_unknown_token": z.boolean().optional(),
    "gemma3n.activation_sparsity_scale": z.null().optional(),
    "gemma3n.altup.active_idx": z.number().optional(),
    "gemma3n.altup.correct_scale": z.boolean().optional(),
    "gemma3n.altup.lr_multiplier": z.number().optional(),
    "gemma3n.altup.num_inputs": z.number().optional(),
    "gemma3n.attention.head_count": z.number().optional(),
    "gemma3n.attention.head_count_kv": z.number().optional(),
    "gemma3n.attention.layer_norm_rms_epsilon": z.number().optional(),
    "gemma3n.attention.shared_kv_layers": z.number().optional(),
    "gemma3n.attention.sliding_window": z.number().optional(),
    "gemma3n.attention.sliding_window_pattern": z.null().optional(),
    "gemma3n.block_count": z.number().optional(),
    "gemma3n.context_length": z.number().optional(),
    "gemma3n.embedding_length": z.number().optional(),
    "gemma3n.embedding_length_per_layer_input": z.number().optional(),
    "gemma3n.feed_forward_length": z.number().optional(),
    "gemma3n.head_dim": z.number().optional(),
    "gemma3n.laurel_rank": z.number().optional(),
    "gemma3n.num_kv_shared_layers": z.number().optional(),
    "gemma3n.rope.freq_base": z.number().optional(),
    "gemma3n.rope.freq_base_local": z.number().optional(),
});
export type ModelInfo = z.infer<typeof ModelInfoSchema>;

export const ProjectorInfoSchema = z.object({
    "clip.has_llava_projector": z.boolean(),
    "clip.has_text_encoder": z.boolean(),
    "clip.has_vision_encoder": z.boolean(),
    "clip.projector_type": z.string(),
    "clip.use_gelu": z.boolean(),
    "clip.vision.attention.head_count": z.number(),
    "clip.vision.attention.layer_norm_epsilon": z.number(),
    "clip.vision.block_count": z.number(),
    "clip.vision.embedding_length": z.number(),
    "clip.vision.feed_forward_length": z.number(),
    "clip.vision.image_mean": z.null(),
    "clip.vision.image_size": z.number(),
    "clip.vision.image_std": z.null(),
    "clip.vision.patch_size": z.number(),
    "clip.vision.projection_dim": z.number(),
    "general.architecture": z.string(),
    "general.description": z.string(),
    "general.file_type": z.number(),
    "general.name": z.string(),
    "general.parameter_count": z.number(),
});
export type ProjectorInfo = z.infer<typeof ProjectorInfoSchema>;

export const TensorSchema = z.object({
    name: z.string(),
    type: TypeSchema,
    shape: z.array(z.number()),
});
export type Tensor = z.infer<typeof TensorSchema>;

export const ModelDetailsResponse = z.object({
    license: z.string().optional(),
    modelfile: z.string(),
    parameters: z.string().optional(),
    template: z.string(),
    details: DetailsClassSchema,
    model_info: ModelInfoSchema,
    tensors: z.array(TensorSchema),
    capabilities: z.array(CapabilitySchema),
    modified_at: z.coerce.date(),
    projector_info: ProjectorInfoSchema.optional(),
    system: z.string().optional(),
});
export type ModelDetailsResponse = z.infer<typeof ModelDetailsResponse>;
